# --------------------------
# Stage 1: Build dependencies
# --------------------------

FROM node:lts-alpine AS build

WORKDIR /server

RUN apk add --no-cache bash openssl

COPY package.json package.json
COPY prisma/ prisma/
# Install only production dependencies
RUN npm install 
RUN npm run db:generate

COPY . .

RUN npm run build

# --------------------------
# Stage 2: Production runtime
# --------------------------

FROM node:lts-alpine AS runner

WORKDIR /app

# Install bash for scripts (optional, Prisma doesn't need glibc)
RUN apk add --no-cache bash openssl

COPY --from=build /server/node_modules node_modules/
COPY --from=build /server/package.json package.json
COPY --from=build /server/prisma/ prisma/
# COPY --from=build /server/generated generated/    
COPY --from=build /server/dist dist/

EXPOSE 8000

CMD [ "sh", "-c", "npm run start"]
